#!/bin/bash

export LD_LIBRARY_PATH=/opt/intel/dlstreamer/lib:/opt/intel/dlstreamer/gstreamer/lib:/opt/intel/openvino_2022/extras/opencv/lib:/opt/intel/openvino_2022/tools/compile_tool:/opt/intel/openvino_2022/runtime/3rdparty/tbb/lib:/opt/intel/openvino_2022/runtime/3rdparty/hddl/lib:/opt/intel/openvino_2022/runtime/lib/intel64
export PYTHONPATH=/opt/intel/openvino_2022/python/python3.8:/opt/intel/openvino_2022/python/python3:/opt/intel/openvino_2022/extras/opencv/python:/usr/lib/x86_64-linux-gnu
export GST_PLUGIN_SCANNER=/opt/intel/dlstreamer/gstreamer/bin/gstreamer-1.0/gst-plugin-scanner
export GST_PLUGIN_PATH=/opt/intel/dlstreamer/lib:/opt/intel/dlstreamer/gstreamer/lib/gstreamer-1.0

exec /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
