#!/bin/bash

cd /opt/fcgi/cgi-bin
. /opt/intel/openvino/bin/setupvars.sh

dbpath() {
    sed -n 's/^auth .* pam_userdb\.so .* db=\([^ ]*\).*$/\1.db/p' $1
}

if [[ -r "/etc/pam.d/${AIAPI_PAM_SERVICE:=http}" &&
      -r "$(dbpath /etc/pam.d/$AIAPI_PAM_SERVICE)" ]]; then
    set -- -a $AIAPI_PAM_SERVICE
else
    set --
fi

exec /usr/sbin/grpc_inference_service "$@" 50001
